"""
QuantConnect (LEAN) QCAlgorithm Exporter.
Generates production-ready QuantConnect LEAN Python algorithm files.
"""

import os


def generate_lean_algorithm(strategy_name: str, symbol: str = "EURUSD", timeframe: str = "Hour") -> str:
    """
    Generates QCAlgorithm Python class code for deployment on LEAN engine.
    """
    qc_symbol = symbol.replace("/", "").replace("_", "")

    code = f'''# QuantConnect LEAN Algorithm Auto-Generated by QuantPipeline
from AlgorithmImports import *

class QuantPipelineStrategy(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2015, 1, 1)
        self.SetCash(100000) # $100,000 Initial Capital

        # Set realistic broker model (Interactive Brokers / Dukascopy)
        self.SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage, AccountType.Margin)

        # Add Asset
        self.symbol = self.AddForex("{qc_symbol}", Resolution.{timeframe.capitalize()}, Market.Oanda).Symbol

        # Indicators
        self.rsi = self.RSI(self.symbol, 14, MovingAverageType.Exponential, Resolution.{timeframe.capitalize()})
        self.bb = self.BB(self.symbol, 20, 2, MovingAverageType.Simple, Resolution.{timeframe.capitalize()})
        self.atr = self.ATR(self.symbol, 14, MovingAverageType.Simple, Resolution.{timeframe.capitalize()})

        # Dynamic Risk Management & Model Parameters
        self.risk_per_trade = 0.01  # 1% Risk per trade
        self.max_daily_drawdown = 0.03  # 3% Max Daily Drawdown Kill Switch
        self.daily_starting_equity = self.Portfolio.TotalPortfolioValue

        self.Schedule.On(self.DateRules.EveryDay(self.symbol), self.TimeRules.AfterMarketOpen(self.symbol, 0), self.ResetDailyMetrics)

    def ResetDailyMetrics(self):
        self.daily_starting_equity = self.Portfolio.TotalPortfolioValue

    def OnData(self, data: Slice):
        if not self.rsi.IsReady or not self.bb.IsReady:
            return

        # Daily Kill Switch Check
        current_drawdown = (self.daily_starting_equity - self.Portfolio.TotalPortfolioValue) / self.daily_starting_equity
        if current_drawdown >= self.max_daily_drawdown:
            self.Liquidate(self.symbol)
            self.Log(f"Daily Kill Switch triggered. Current drawdown: {{current_drawdown:.2%}}")
            return

        price = data[self.symbol].Close
        holdings = self.Portfolio[self.symbol].Quantity

        # Trading Logic for {strategy_name}
        if holdings == 0:
            if price < self.bb.LowerBand.Current.Value and self.rsi.Current.Value < 30:
                quantity = self.CalculateOrderQuantity(self.symbol, 0.02)
                self.MarketOrder(self.symbol, quantity)
                self.StopMarketOrder(self.symbol, -quantity, price - (self.atr.Current.Value * 1.5))
                self.LimitOrder(self.symbol, -quantity, price + (self.atr.Current.Value * 3.0))

            elif price > self.bb.UpperBand.Current.Value and self.rsi.Current.Value > 70:
                quantity = self.CalculateOrderQuantity(self.symbol, -0.02)
                self.MarketOrder(self.symbol, quantity)
                self.StopMarketOrder(self.symbol, -quantity, price + (self.atr.Current.Value * 1.5))
                self.LimitOrder(self.symbol, -quantity, price - (self.atr.Current.Value * 3.0))

        elif holdings > 0 and price >= self.bb.MiddleBand.Current.Value:
            self.Liquidate(self.symbol)

        elif holdings < 0 and price <= self.bb.MiddleBand.Current.Value:
            self.Liquidate(self.symbol)
'''
    return code


def export_lean_algorithm(strategy_name: str, symbol: str, output_path: str):
    code = generate_lean_algorithm(strategy_name, symbol)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(code)
    return output_path
